### ISSUE TITLE
introduce gulp workflow?

### ISSUE THREAD

**Issue by zhuangya** [manifestinteractive/jqvmap#177]
#### Overview:

`jquery.vmap.js` is too big file now, i purpose to cut it into pieces and build and compress the production by `gulp`

#### Acceptance Criteria:

change file structure to:
```
└── src
    ├── css
    ├── data
    ├── js
    └── maps
        └── continents

```

and concat, build, compress files in `js` by gulp
#### Steps to Duplicate _( required for detects )_:

N/A

#### Relevant Documentation _( optional )_

- [gulp](http://gulpjs.com/)
- [gulp requirejs](https://www.npmjs.com/package/gulp-requirejs)
- [gulp uglify](https://www.npmjs.com/package/gulp-uglify)

#### TODO:

- [ ] better directory structure
- [x] gulp compress task
- [ ] split `jquery.vmap.js` file
- [ ] gulp build task powered by `gulp-requirejs` maybe?
- [ ] update `bower.json` and `package.json` accordingly

**Comment by zhuangya** [comment]
so, @manifestinteractive how do you think?

**Comment by manifestinteractive** [comment]
@zhuangya This is actually how I do most of the files and was something I intended to do someday.  I already have a base foundation I use on other project, e.g. https://github.com/manifestinteractive/mobile-app-template

**Comment by zhuangya** [comment]
@manifestinteractive neat. actually i've done something by now. i'll update a TODO list in the topic, when i finish, i send PR

**Comment by manifestinteractive** [comment]
I introduced grunt as a way to build the project and separated the main file into smaller method specific files.  I am closing out this ticket since it has been implemented via another method.
